*----------------------------------*
*--                              --*
*-- Defines for Managers library --*
*--                              --*
*----------------------------------*


*--
*-- General library constants.
*--

*-- Used key codes.
#DEFINE	c_KEY_TAB			9
#DEFINE	c_KEY_ENTER			13
#DEFINE	c_KEY_SHIFT_TAB		15
#DEFINE	c_KEY_ESC			27

*-- nState constants.
#DEFINE	c_AUTOSIZE_BEFORE	1
#DEFINE	c_AUTOSIZE_AFTER	2

*-- nTextType constants.
#DEFINE	c_TEXT_TYPE_MSG		1
#DEFINE	c_TEXT_TYPE_ERROR	2
#DEFINE	c_TEXT_TYPE_WARNING	3
#DEFINE	c_TEXT_TYPE_HELP	4
#DEFINE	c_TEXT_TYPE_TOOLTIP	5
z

*--
*-- bindEventHandler class.
*--

*-- bindEventHandler errors.
#DEFINE	c_BINDEVENTHANDLER_ERROR_PROPERTY_NUMBER		-1
#DEFINE	c_BINDEVENTHANDLER_ERROR_PROPERTY_MESSAGE		'Property EventName is empty.'


*--
*-- findBox class.
*--

*-- findBox flags.
#DEFINE	c_FINDBOX_FLAG_NONE								0
#DEFINE	c_FINDBOX_FLAG_RESET							2^0
#DEFINE	c_FINDBOX_FLAG_ORDER							2^1
#DEFINE	c_FINDBOX_FLAG_REVERSED							2^2

*-- findBox search direction.
#DEFINE	c_FINDBOX_SEARCH_DIRECTION_FORWARD				0
#DEFINE	c_FINDBOX_SEARCH_DIRECTION_BACKWARD				1

*-- Tool tips.
#DEFINE	c_FINDBOX_TOOLTIP_HELP_ON_DEMAND				9501
#DEFINE	c_FINDBOX_TOOLTIP_HELP_ALWAYS_VISIBLE			9502
#DEFINE	c_FINDBOX_TOOLTIP_NEXT							9503
#DEFINE	c_FINDBOX_TOOLTIP_PREVIOUS						9504


*--
*-- mngrGrid class.
*--

*-- mngrGrid component basic constants.
#DEFINE	c_MNGRGRID_SUPPORTED_CLASS_LIST					'Grid'
#DEFINE	c_MNGRGRID_VERSION								'1.0.0'
#DEFINE	c_MNGRGRID_UUID									'26ea386b-1569-4526-a6c4-edf45379c9ee'

*-- mngrGrid autosize.
#DEFINE	c_MNGRGRID_AUTOSIZE_ALL							0
#DEFINE	c_MNGRGRID_AUTOSIZE_EXCEPT						1
#DEFINE	c_MNGRGRID_AUTOSIZE_ONLY						2

*-- mngrGrid dynamic properties mode.
#DEFINE	c_MNGRGRID_DINAMIC_MODE_RUDE					0
#DEFINE	c_MNGRGRID_DINAMIC_MODE_POLITE					1
#DEFINE	c_MNGRGRID_DINAMIC_MODE_RESPECTFUL				2

*-- mngrGrid footer.
#DEFINE	c_MNGRGRID_FOOTER_HEIGHT						25
#DEFINE	c_MNGRGRID_FOOTER_MARGIN_BOTTOM					1
#DEFINE	c_MNGRGRID_FOOTER_MARGIN_TOP					1
#DEFINE	c_MNGRGRID_FOOTER_BACKCOLOR						Rgb(192, 192, 192)
#DEFINE	c_MNGRGRID_FOOTER_FORECOLOR						Rgb(0, 0, 0)

*-- mngrGrid order.
#DEFINE	c_MNGRGRID_SORT_ASC								'ASC'
#DEFINE	c_MNGRGRID_SORT_DES								'DES'

*-- mngrGrid sort result.
#DEFINE	c_MNGRGRID_SORT_RESULT_FAIL						-1
#DEFINE	c_MNGRGRID_SORT_RESULT_SORT_AND_ORDER			0
#DEFINE	c_MNGRGRID_SORT_RESULT_ONLY_SORT				1

*-- mngrGrid errors.
#DEFINE	c_MNGRGRID_ERROR_SEARCH_DATE_NUMBER				9001
#DEFINE	c_MNGRGRID_ERROR_SEARCH_DATE_MESSAGE			'Not a valid date'
#DEFINE	c_MNGRGRID_ERROR_SEARCH_DATETIME_NUMBER			9002
#DEFINE	c_MNGRGRID_ERROR_SEARCH_DATETIME_MESSAGE		'Not a valid date or datetime'
#DEFINE	c_MNGRGRID_ERROR_SEARCH_LOGICAL_NUMBER			9003
#DEFINE	c_MNGRGRID_ERROR_SEARCH_LOGICAL_MESSAGE			'Logical fields are not supported'
#DEFINE	c_MNGRGRID_ERROR_SEARCH_MEMO_NUMBER				9004
#DEFINE	c_MNGRGRID_ERROR_SEARCH_MEMO_MESSAGE			'Memo fields are not supported'
#DEFINE	c_MNGRGRID_ERROR_SEARCH_NUMBER_NUMBER			9005
#DEFINE	c_MNGRGRID_ERROR_SEARCH_NUMBER_MESSAGE			'Not a valid number'
#DEFINE	c_MNGRGRID_ERROR_SEARCH_GENERIC_NUMBER			9006
#DEFINE	c_MNGRGRID_ERROR_SEARCH_GENERIC_MESSAGE			'Value or field not valid for search'
#DEFINE	c_MNGRGRID_ERROR_SEARCH_GENERIC_TYPE_NUMBER		9007
#DEFINE	c_MNGRGRID_ERROR_SEARCH_GENERIC_TYPE_MESSAGE	'Field type are not supported'
#DEFINE	c_MNGRGRID_ERROR_SEARCH_TEXT_NUMBER				9008
#DEFINE	c_MNGRGRID_ERROR_SEARCH_TEXT_MESSAGE			'Not a valid text'

*-- mngrGrid warnings.
#DEFINE	c_MNGRGRID_WARNING_NO_RECORDS_NUMBER			9201
#DEFINE	c_MNGRGRID_WARNING_NO_RECORDS_MESSAGE			'No records found'
#DEFINE	c_MNGRGRID_WARNING_NO_MORE_RECORDS_NUMBER		9202
#DEFINE	c_MNGRGRID_WARNING_NO_MORE_RECORDS_MESSAGE		'No more records found'
