*-- Defines for Managers library.

*--
*-- bindEventHandler class.
*--

*-- bindEventHandler errors.
#DEFINE	c_BINDEVENTHANDLER_ERROR_PROPERTY_NUMBER	-1
#DEFINE	c_BINDEVENTHANDLER_ERROR_PROPERTY_MESSAGE	'Property EventName is empty.'


*--
*-- findBox class.
*--

*-- findBox search direction.
#DEFINE	c_FINDBOX_SEARCH_DIRECTION_FORWARD	0
#DEFINE	c_FINDBOX_SEARCH_DIRECTION_BACKWARD	1

*-- findBox flags.
#DEFINE	c_FINDBOX_FLAG_NONE					0
#DEFINE	c_FINDBOX_FLAG_RESET				2^0
#DEFINE	c_FINDBOX_FLAG_ORDER				2^1
#DEFINE	c_FINDBOX_FLAG_START_OR_CONTAINS	2^2
#DEFINE	c_FINDBOX_FLAG_EXACT				2^3
#DEFINE	c_FINDBOX_FLAG_REVERSED				2^5

*--
*-- mngrGrid class.
*--

*-- mngrGrid autosize.
#DEFINE	c_MNGRGRID_AUTOSIZE_ALL				0
#DEFINE	c_MNGRGRID_AUTOSIZE_EXCEPT			1
#DEFINE	c_MNGRGRID_AUTOSIZE_ONLY			2

*-- mngrGrid dynamic properties mode.
#DEFINE	c_MNGRGRID_DINAMIC_MODE_RUDE		0
#DEFINE	c_MNGRGRID_DINAMIC_MODE_POLITE		1
#DEFINE	c_MNGRGRID_DINAMIC_MODE_RESPECTFUL	2

*-- mngrGrid footer.
#DEFINE	c_MNGRGRID_FOOTER_HEIGHT			25
#DEFINE	c_MNGRGRID_FOOTER_MARGIN_BOTTOM		1
#DEFINE	c_MNGRGRID_FOOTER_MARGIN_TOP		1
#DEFINE	c_MNGRGRID_FOOTER_BACKCOLOR			Rgb(192, 192, 192)
#DEFINE	c_MNGRGRID_FOOTER_FORECOLOR			Rgb(0, 0, 0)

*-- mngrGrid order.
#DEFINE	c_MNGRGRID_SORT_ASC					'ASC'
#DEFINE	c_MNGRGRID_SORT_DES					'DES'

*-- mngrGrid sort result.
#DEFINE	c_MNGRGRID_SORT_RESULT_FAIL				-1
#DEFINE	c_MNGRGRID_SORT_RESULT_SORT_AND_ORDER	0
#DEFINE	c_MNGRGRID_SORT_RESULT_ONLY_SORT		1

*-- mngrGrid errors.
#DEFINE	c_MNGRGRID_ERROR_SEARCH_DATE_NUMBER				9001
#DEFINE	c_MNGRGRID_ERROR_SEARCH_DATE_MESSAGE			'Not a valid date'
#DEFINE	c_MNGRGRID_ERROR_SEARCH_DATETIME_NUMBER			9002
#DEFINE	c_MNGRGRID_ERROR_SEARCH_DATETIME_MESSAGE		'Not a valid date or datetime'
#DEFINE	c_MNGRGRID_ERROR_SEARCH_LOGICAL_NUMBER			9003
#DEFINE	c_MNGRGRID_ERROR_SEARCH_LOGICAL_MESSAGE			'Logical fields are not supported'
#DEFINE	c_MNGRGRID_ERROR_SEARCH_MEMO_NUMBER				9004
#DEFINE	c_MNGRGRID_ERROR_SEARCH_MEMO_MESSAGE			'Memo fields are not supported'
#DEFINE	c_MNGRGRID_ERROR_SEARCH_NUMBER_NUMBER			9005
#DEFINE	c_MNGRGRID_ERROR_SEARCH_NUMBER_MESSAGE			'Not a valid number'
#DEFINE	c_MNGRGRID_ERROR_SEARCH_GENERIC_NUMBER			9006
#DEFINE	c_MNGRGRID_ERROR_SEARCH_GENERIC_MESSAGE			'Value or field not valid for search'
#DEFINE	c_MNGRGRID_ERROR_SEARCH_GENERIC_TYPE_NUMBER		9007
#DEFINE	c_MNGRGRID_ERROR_SEARCH_GENERIC_TYPE_MESSAGE	'Field type are not supported'
#DEFINE	c_MNGRGRID_ERROR_SEARCH_TEXT_NUMBER				9008
#DEFINE	c_MNGRGRID_ERROR_SEARCH_TEXT_MESSAGE			'Not a valid text'

*-- mngrGrid warnings.
#DEFINE	c_MNGRGRID_WARNING_NO_RECORD_NUMBER				9501
#DEFINE	c_MNGRGRID_WARNING_NO_RECORD_MESSAGE			'No record found'






*--
*-- Keys.
*--

#DEFINE	c_KEY_TAB			9
#DEFINE	c_KEY_ENTER			13
#DEFINE	c_KEY_SHIFT_TAB		15
#DEFINE	c_KEY_ESC			27
